Make twitter db design
private-ryomann/twitter_db_design pull request #1
Opened 2023-07-10 11:34 UTC by private-ryomann

## やったこと
TwitterのDB設計を行いました。

## 動作確認方法
1. git clone する
2. プロジェクトルートでdocker run -i ghcr.io/burntsushi/erd:latest < twitter.er >| out.pdf

## その他
確認よろしくお願いいたします。

2023-07-16 14:27 UTC, ihatov08 requested changes
通知機能が抜けているので、修正お願いします！

2023-07-18 00:41 UTC, private-ryomann commented
> 通知機能が抜けているので、修正お願いします！
通知機能はアプリケーション側で実装するものだと思っていました。

通知機能⇒FollowsとLikesをDBに追加するタイミングでユーザーに通知を行う
特定のユーザーの過去の通知一覧⇒特定のユーザーIDのFollowsテーブルとLikesテーブルを時系列順に並べれば作成可能

通知テーブルを作成する意図としては
特定のユーザーの過去の通知をSQL1文でとってこれるのでアプリケーション側で時系列順に並べるよりも、管理もパフォーマンスもいいという認識で大丈夫でしょうか？

2023-07-18 03:57 UTC, ihatov08 commented
> > 通知機能が抜けているので、修正お願いします！
> 
> 通知機能はアプリケーション側で実装するものだと思っていました。
> 
> 通知機能⇒FollowsとLikesをDBに追加するタイミングでユーザーに通知を行う 特定のユーザーの過去の通知一覧⇒特定のユーザーIDのFollowsテーブルとLikesテーブルを時系列順に並べれば作成可能
> 
> 通知テーブルを作成する意図としては 特定のユーザーの過去の通知をSQL1文でとってこれるのでアプリケーション側で時系列順に並べるよりも、管理のしやすさとパフォーマンスがいいという認識で大丈夫でしょうか？

今回はパフォーマンスうんぬんよりも、テーブルとして定義する前提でテーブル設計をしてほしいです！

2023-07-18 12:14 UTC, private-ryomann commented
> 今回はパフォーマンスうんぬんよりも、テーブルとして定義する前提でテーブル設計をしてほしいです！

通知テーブルを追加しました！確認お願いします。

2023-07-18 12:18 UTC, ihatov08 commented on twitter.er
> +    notificated_id {label: "bigint, not null, FK(Follows, Likes)"}
複数テーブルに外部キー制約は付与できないです。

2023-07-18 14:36 UTC, private-ryomann commented on twitter.er
> +    notificated_id {label: "bigint, not null, FK(Follows, Likes)"}
FK(Follows, Likes)を無くすだけでもできたと思いますが
- notificated_idに何が入るかが分かりずらい
- notificated_typeのルールを覚えないといけない

のはあまりよくないと思ったので
Ntoficationsテーブルと関連のあるLikes, Followsテーブルの中間テーブルを作成して、直感的に関連が分かりやすく変更しました！

2023-07-19 08:59 UTC, ihatov08 commented on twitter.er
> +    notificated_id {label: "bigint, not null, FK(Follows, Likes)"}
> FK(Follows, Likes)を無くすだけでもできたと思いますが

わたしはこちらでよいと思いました！

2023-07-19 10:05 UTC, private-ryomann commented on twitter.er
> +    notificated_id {label: "bigint, not null, FK(Follows, Likes)"}
さすがに中間テーブルを作るのは大げさなんですね。  
元に戻しました。確認お願いします！

2023-07-20 06:02 UTC, ihatov08 approved these changes
確認しました、LGTMです！

2023-07-20 08:00 UTC, private-ryomann commented
> 確認しました、LGTMです！

確認ありがとうございました！！！

2023-07-20 08:00 UTC, merged